(* ::Package:: *)

(* ::Input:: *)
(*(* Parameters *)*)
(*rEarth = 1;*)
(*rSatellite = 2.5; (* Not to scale for GEO, but it is clearer with a closer satellite *)*)
(**)
(*phiOne = 50 Degree;*)
(*lambdaOne = 90 Degree;*)
(*phiTwo = -30 Degree;*)
(*lambdaTwo =45 Degree;*)
(**)
(*satLongitude =90;*)
(**)
(*gs1 =rEarth{Cos[phiOne] Cos[lambdaOne],Cos[phiOne] Sin[lambdaOne],Sin[phiOne]};*)
(*gs2 =rEarth{Cos[phiTwo] Cos[lambdaTwo],Cos[phiTwo] Sin[lambdaTwo],Sin[phiTwo]};*)
(**)
(*myGraphic = Graphics3D[{*)
(*(* Earth *)*)
(*Opacity[0.25],Green,Sphere[{0,0,0},rEarth],*)
(*Opacity[1.0], Black, PointSize[0.02], Point[{0,0,0}],*)
(**)
(*(* GEO Satellite *)*)
(*Red, Point[{0,rSatellite,0}],*)
(*Text[Style["Satellite",16, Bold], {0,rSatellite+0.05,0.2}],*)
(*Thick,Arrowheads[0.025], Arrow[{{0,0,0},{0,rSatellite,0}}],Arrowheads[0.03],*)
(*Text[Style[OverVector["s"],16,Bold],{0,1.3,0.15}],*)
(**)
(*(* Ground Station 1 *)*)
(*Blue, Point[gs1],*)
(*Text[Style["Ground Station 1",16, Bold], {gs1[[1]],gs1[[2]]+0.38,gs1[[3]]+0.15}],*)
(*Arrow[{{0,0,0},gs1}],*)
(*Text[Style[OverVector[Subscript["g",1]],16,Bold],{0,0.25,0.55}],*)
(**)
(**)
(*(* Ground Station 2 *)*)
(*Blue, Point[gs2],*)
(*Text[Style["Ground Station 2",16, Bold], {gs2[[1]],gs2[[2]]+0.38,gs2[[3]]-0.1}],*)
(*Arrow[{{0,0,0},gs2}],*)
(*Text[Style[OverVector[Subscript["g",2]],16,Bold],{0,0.2,-0.5}],*)
(**)
(*(* Radio signal paths *)*)
(*Darker[Orange],*)
(*Arrowheads[0.015],Arrow[{gs1,{0,rSatellite,0}}],*)
(*Arrow[{gs2,{0,rSatellite,0}}],Arrowheads[0.04],*)
(*Text[Style[OverVector[Subscript["d",1]],14,Bold],{0,1.4,0.6}],*)
(*Text[Style[OverVector[Subscript["d",2]],14,Bold],{0,1.6,-0.4}],*)
(**)
(**)
(*(* Equator line *)*)
(*Black, Thick, Dashing[{0.05,0.05}],*)
(*Line@Table[{rEarth Cos[t],rEarth Sin[t],0},{t,0,(2 Pi),0.001}],*)
(*Text[Style["Equator",14], {rEarth+0.3,-0.05,0}],*)
(**)
(**)
(*(* Axis of rotation *)*)
(*Dashing[None],*)
(*Arrow[{{0,0,0},{0,0,2}}],*)
(*Arrow[{{0,0,0},{0,0,-2}}],*)
(*Text[Style["Axis of Rotation",16], {0,0,2.1}],*)
(**)
(*(* Angles of Separation *)*)
(*Purple,*)
(*Line@Table[{0,0.3Cos[t],0.3Sin[t]},{t,0,phiOne,0.001}],*)
(*Line@Table[{-0.25Cos[-1.5t]Cos[t],-0.25Sin[-1.5t]Cos[t],0.25Sin[t]},{t,Pi,Pi+Pi/6,0.001}], *)
(*(* Forgive me for this disgusting math, I didn't want to do proper calculations so I started with*)
(*the fact that in this specific case for gs2, lambda = -1.5 phi an used the conversian from latitude/longitude to cartesian*)
(*equations to get a visual. Then I noticed that the segment of the parameterized line I wanted existed, just in a different location.*)
(*So I reflected along the x and y axes to get it to where I wanted it, then just found the time range for only that segment. Basically trial and error.*)
(**)
(*Weird process but the results speak for themselves! (this took way too long tho lol)*)
(* *)*)
(*Text[Style[Subscript["\[Beta]",1],14,Bold],{0,0.4,0.15}],*)
(*Text[Style[Subscript["\[Beta]",2],14,Bold],{0.15,0.35,-0.08}],*)
(**)
(*},*)
(**)
(*Boxed->False,*)
(*Axes->False,*)
(*PlotRange->All,*)
(*ImageSize->Large,*)
(*Lighting->"Neutral",*)
(*ViewPoint->{4,1,1},*)
(*ViewVertical->{0,0,1},*)
(*Background -> GrayLevel[0.9]*)
(**)
(*]*)


(* ::Input:: *)
(*Export["GEO Diagram.png", myGraphic, ImageResolution-> 300];*)
