(* ::Package:: *)

(* ::Input:: *)
(*(* Parameters *)*)
(*phi = 60 Degree;*)
(*lambda = 50 Degree;*)
(*r = 1;*)
(*p=r {Cos[phi] Cos[lambda],Cos[phi] Sin[lambda],Sin[phi]};*)
(*mag = N[Sqrt[p[[1]]^2 + p[[2]]^2]];*)
(**)
(*(*Arc for phi:from projection onto xy-plane up to the radius vector*)*)
(*phiArc[t_]:=r {Cos[t] Cos[lambda],Cos[t] Sin[lambda],Sin[t]};*)
(*phiArcPts=Table[phiArc[t],{t,0,phi,phi/30}];*)
(**)
(*(*Arc for lambda:in the xy-plane*)*)
(*lambdaArc[t_]:={Cos[t],Sin[t],0};*)
(*lambdaArcPts=Table[lambdaArc[t],{t,0,lambda,lambda/30}];*)
(**)
(*myGraphic = Graphics3D[{*)
(*(* Sphere *)*)
(*Opacity[0.25],White,Sphere[{0,0,0},r],*)
(**)
(*(* Everything Else *)*)
(**)
(*(* Grid *)*)
(*Opacity[1.0], Black,Thick,*)
(*Arrow[{{0,0,0},{2,0,0}}],*)
(*Arrow[{{0,0,0},{0,2,0}}],*)
(*Arrow[{{0,0,0},{0,0,2}}],*)
(*Text[Style["x",16], {2.1,0,0}],*)
(*Text[Style["y",16], {0,2.1,0}],*)
(*Text[Style["z",16], {0,0,2.1}],*)
(**)
(**)
(*Red, Arrow[{{0,0,0},p}],*)
(*Black, PointSize[0.02], Point[p],*)
(**)
(*(*Projection of the radius vector onto xy-plane*)*)
(*Dashed,Darker[Red],Line[{{0,0,0},{p[[1]]/mag,p[[2]]/mag,0}}],*)
(*(*Line[{{p[[1]],p[[2]],0},p}],*)*)
(**)
(*(*Phi arc*)*)
(*Dashed,Thick,Darker[Green],Line[phiArcPts],Text[Style["\[Phi]",20,Darker[Green]],1.2r {Cos[phi/2] Cos[lambda],Cos[phi/2] Sin[lambda],Sin[phi/2]}],*)
(**)
(*(*Lambda arc*)*)
(*Thick,Purple,Line[lambdaArcPts],Text[Style["\[Lambda]",20,Purple],1.4{Cos[lambda/2],Sin[lambda/2],0.08}]*)
(**)
(*},*)
(**)
(*Boxed->False,*)
(*Axes->False,*)
(*PlotRange->All,*)
(*ImageSize->Large,*)
(*Lighting->"Neutral",*)
(*ViewPoint->{4,1,2},*)
(*ViewVertical->{0,0, 1},*)
(*Background -> GrayLevel[0.95]*)
(**)
(*]*)
(**)


(* ::Input:: *)
(*Export["toCartesian.png", myGraphic, ImageResolution-> 300];*)
