(* ::Package:: *)

(* ::Input:: *)
(*rEarth = 1;*)
(*rSatellite = N[35801401.9/6371000];*)
(*satLocation = {rSatellite, 0, 0};*)
(**)
(*myGraphic = Graphics3D[{*)
(*Opacity[1.0], Green, Sphere[{0,0,0},rEarth],*)
(*Gray, Thick, Dashing[{0.06,0.04}],Line@Table[{rSatellite Cos[t],rSatellite Sin[t],0},{t,0.05,(2 Pi)0.99,0.001}],*)
(*Red,PointSize[0.03],Point[satLocation],*)
(*White,Dashing[{}], Line[{{rEarth,0,0},{0.96 rSatellite,0,0}}],*)
(**)
(*Blue,Text[Style["Earth", 18],{0,0,0}],*)
(*White,Text[Style["GEO Satellite", 18],{rSatellite+1.6,0,0}],*)
(*Text[Style["h = ~35,800 km", 16],{3,0.25,0}],*)
(**)
(*},*)
(*Boxed->False,*)
(*Axes->False,*)
(*PlotRange->All,*)
(*ImageSize->Large,*)
(*Lighting->"Neutral",*)
(*ViewPoint->{0,0,5},*)
(*ViewVertical->{0,1,0},*)
(*Background -> GrayLevel[0.1]*)
(*]*)


(* ::Input:: *)
(*Export["toScale.png", myGraphic, ImageResolution-> 300];*)
